apiVersion: keystone.openstack.org/v1beta1
kind: KeystoneAPI
metadata:
  name: keystone
spec:
  adminProject: admin
  adminRole: admin
  adminUser: admin
  containerImage: quay.io/tripleozedcentos9/openstack-keystone:current-tripleo
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: keystone
  debug:
    bootstrap: false
    dbSync: false
    service: false
  preserveJobs: false
  region: regionOne
  secret: keystone-secret
  resources:
    requests:
      memory: "500Mi"
      cpu: "1.0"
